/**
 * @jest-environemnt node
 */

import { join } from "path";
import { cwd } from "process";

import ManagerClass from "@/feature/Manager/manager";

describe("Manager test", () => {
  it("index method test", () => {
    const path = join(cwd(), "src", "test", "articles");
    const Manager = new ManagerClass(path);

    const articles = Manager.index();

    expect(articles).toHaveLength(1);
  });

  it("show method test", () => {
    const path = join(cwd(), "src", "test", "articles");
    const Manager = new ManagerClass(path);

    const article = Manager.show("test");

    expect(article).toHaveProperty(
      "title",
      "日本語フェイクニュースデータセット",
    );
    expect(article).toHaveProperty("createdAt", "2023/03/14");
    expect(article).toHaveProperty("readingTime", 4);
    expect(article).toHaveProperty("publish", true);
    expect(article).toHaveProperty(
      "content",
      '# 日本語フェイクニュースデータセット\n\n## 日本語フェイクニュースデータセット\n\n### 日本語フェイクニュースデータセット\n\n#### 日本語フェイクニュースデータセット\n日本語のニュース記事と、[GPT-2日本語版](https://github.com/tanreinama/gpt2-japanese)のモデルで生成された、ディープフェイク記事からなるデータセットです。\n    \n内容は、[クリエイティブ・コモンズ（改変可）](https://creativecommons.jp/)ライセンスで公開されている、[ウィキニュース日本語版](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8)の記事と、[GPT-2日本語版](https://github.com/tanreinama/gpt2-japanese)のモデルが生成したディープフェイク記事を合わせた、混合コーパスです。\n\n全てのデータは、オリジナルの記事かフェイク記事であるかのタグがつけられており、\n\n- オリジナルの記事（人間が執筆した）\n- 部分的にフェイク（記事の後半をGPT-2モデルが生成した）\n- 完全にフェイク（記事の全体をGPT-2モデルが生成した）\n\nのいずれかに該当します。\n\n![image](https://via.placeholder.com/640x480.png/004466?text=animals+omnis)\n\nCSVファイルのコラムは、以下の通りです。\n\n| コラム名   | 意味   |\n| ---------- | ------------------------------------------------------------ |\n| id   | ユニークID   |\n| context    | 記事の文章（UTF-8エンコード）  |\n| isfake     | 記事がフェイクであるかどうかのタグ：<br />0：オリジナルの記事<br />1：部分的にフェイク<br />2：完全にフェイク |\n| nchar_real | 記事の中の、人間が執筆した部分の文字数     |\n| ncahr_fake | 記事の中の、モデルが生成した部分の文字数   |\n\n\n\n[ウィキニュース日本語版](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8)は、「[クリエイティブ・コモンズ](https://ja.wikipedia.org/wiki/クリエイティブ・コモンズ)-表示-2.5 [CC-by-2.5](https://creativecommons.org/licenses/by/2.5/deed.ja)  以降」（ただし2005年9月24日までに投稿されたものは「[クリエイティブ・コモンズ](https://ja.wikipedia.org/wiki/クリエイティブ・コモンズ)-表示-2.1-日本以降」([CC-by-2.1-jp](https://creativecommons.org/licenses/by/2.1/jp/)  or later)）で公開されているため、記事を改編して、「途中までオリジナルで、残りはAIが生成した記事」というデータを作成することが出来ます。\n\n「部分的にフェイク」な記事は、途中まで[ウィキニュース日本語版](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8)のオリジナル記事で、途中からAIが生成した記事で置き換えられたものです。\n\nこのデータセットは、フェイクニュースを検出するAIの開発のために作成されました。\n\n使用したGPT-2モデルは、[GPT-2日本語版](https://github.com/tanreinama/gpt2-japanese)プロジェクトが公開しているmediumモデルそのままで、専用のファインチューニング等は行っていません。\n\n[ウィキニュース日本語版](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8)に特徴的な、「新聞によると～」のような接頭詞は、モデルとは別に追加されました。\n\n\n\n# Japanese FakeNews Dataset\n\n```typescript\nconst a = "Hello"\n```\n\n\nThis dataset consists of news articles in Japanese and deep fake articles generated by the [GPT-2 Japanese](https://github.com/tanreinama/gpt2-japanese) model.\n\nThis is a mixed corpus, consisting of the original articles are from the [Japanese version of Wikinews](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8), which is released under a [Creative Commons (modification allowed)](https://creativecommons.org/) license and the data generated by the [GPT-2 Japanese](https://github.com/tanreinama/gpt2-japanese) model.\n\nAll data will be tagged as either original or fake articles and will fall into one of the following categories.\n\n- Original article (written by humans)\n- Partially fake (the second half of the article was generated by the GPT-2 model)\n- Completely fake (the entire article was generated by the GPT-2 model)\n\n\n\nThe columns in the CSV file are as follows.\n\n| Column name | Meaning|\n| ----------- | ------------------------------------------------------------ |\n| id    | unique ID    |\n| context     | text of the article (UTF-8 encoded)  |\n| isfake| Tag whether the article is fake or not: <br />0: Original article <br />1: Partially fake <br />2: Completely fake |\n| nchar_real  | Number of characters in the human-authored part of the article. |\n| ncahr_fake  | Number of characters in the model-generated part of the article. |\n\n```typescript\nconsole.log(\'Hello World\')\n```\n\nSince the  [Japanese version of Wikinews](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8) is published under "[Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons) Attribution 2.5 Generic ([CC BY 2.5](https://creativecommons.org/licenses/by/2.5/deed.en))" (however, articles posted before September 24, 2005 are published under "[Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons) Attribution 2.1 Japan ([CC BY 2.1 JP](https://creativecommons.org/licenses/by/2.1/jp/deed.en))"), it is possible to revise an article and create a data set that is "original until the middle, and the rest of the article is AI-generated".\n\nThe "Partially fake" article contains original articles on  [Japanese version of Wikinews](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8) until halfway through, when it is replaced by an AI-generated article.\n\nThis data set was created for the development of an AI to detect fake news.\n\nThe GPT-2 model used is the same as the medium model published by the [GPT-2 Japanese](https://github.com/tanreinama/gpt2-japanese) project, and no special fine tuning was done.\n\nThe prefix "新聞によると～", which is characteristic of the [Japanese version of Wikinews](https://ja.wikinews.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8), has been added independently of the model.\n',
    );
  });
});
